# Generated by Django 3.1 on 2020-08-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price amount')),
                ('currency', models.CharField(choices=[('USD', 'USD')], default='USD', max_length=3, verbose_name='Currency')),
            ],
        ),
    ]
