# Generated by Django 3.1 on 2020-08-27 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200815_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField(verbose_name='Response data')),
                ('gateway', models.CharField(choices=[('paypal', 'paypal')], default='paypal', max_length=16, verbose_name='Gateway')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=16, verbose_name='Status')),
                ('payment_id', models.CharField(max_length=64, verbose_name='Payment ID')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payment.invoice')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
