# Generated by Django 3.1 on 2020-09-02 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('payment', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='', max_length=3, verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.customer', verbose_name='Customer'),
            preserve_default=False,
        ),
    ]
