# Generated by Django 3.1 on 2020-09-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_description'),
        ('payment', '0004_auto_20200902_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='service',
        ),
        migrations.AddField(
            model_name='invoice',
            name='service',
            field=models.ManyToManyField(to='services.Service', verbose_name='Invoice'),
        ),
    ]
