# Generated by Django 3.1 on 2020-08-07 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.PositiveSmallIntegerField(verbose_name='Minimum age')),
                ('max', models.PositiveSmallIntegerField(verbose_name='Maximum age')),
            ],
            options={
                'verbose_name': ('Age range',),
                'verbose_name_plural': 'Age ranges',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('image', models.ImageField(max_length=256, upload_to='photos', verbose_name='Service image')),
                ('schedule', models.JSONField(verbose_name='Schedule')),
                ('age_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.agerange', verbose_name='Age range')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.price', verbose_name='Price')),
            ],
            options={
                'verbose_name': ('Service',),
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='homeworks', verbose_name='Homework file')),
                ('description', models.TextField(verbose_name='Description')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': ('Homerwork',),
                'verbose_name_plural': 'Homeworks',
            },
        ),
    ]
