# Generated by Django 3.1 on 2020-08-15 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.CharField(max_length=64, verbose_name='Minimum')),
                ('max', models.CharField(max_length=64, verbose_name='Maximum')),
            ],
            options={
                'verbose_name': 'Grade range',
                'verbose_name_plural': 'Grade ranges',
            },
        ),
        migrations.CreateModel(
            name='ServiceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Service Level',
                'verbose_name_plural': 'Service Levels',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('image', models.ImageField(max_length=256, upload_to='services', verbose_name='Service image')),
                ('schedule', models.JSONField(verbose_name='Schedule')),
                ('grade_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.graderange', verbose_name='Grade range')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicelevel', verbose_name='Service level')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.price', verbose_name='Price')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype', verbose_name='Service type')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='homeworks', verbose_name='Homework file')),
                ('description', models.TextField(verbose_name='Description')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Homerwork',
                'verbose_name_plural': 'Homeworks',
            },
        ),
    ]
