# Generated by Django 3.1 on 2020-08-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agerange',
            options={'verbose_name': 'Age range', 'verbose_name_plural': 'Age ranges'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Homerwork', 'verbose_name_plural': 'Homeworks'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(max_length=256, upload_to='services', verbose_name='Service image'),
        ),
    ]
